# Generated by Django 5.0.7 on 2024-08-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=' ', upload_to='jobphoto/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
